### ISSUE TITLE
Adding a validation before creating udf expression

### ISSUE THREAD

**Issue by shlee0605** [shlee0605/peloton#3]
We need to add the validation before creating udf expression at the following spot.

https://github.com/shlee0605/peloton/blob/udf/src/backend/bridge/dml/expr/expr_transformer.cpp#L306

We will have to retrieve some information from function manager (fmgr.cpp) with function_id.

Let's first check the following things.
- if function_id is valid
- which language is used for this function

Refer this page
http://www.postgresql.org/docs/9.5/static/catalog-pg-proc.html

**Comment by shlee0605** [comment]
You can refer the following code to understand how to get access to the information in `pg_proc`.
https://github.com/shlee0605/peloton/blob/master/src/postgres/backend/utils/fmgr/fmgr.cpp#L2316

**Comment by shlee0605** [comment]
You can refer how to get access to the pg_proc information from the following line.

**Comment by shlee0605** [comment]
So, let's try to keep the old code and we just catch c-udf functions for now.

```
if(!retval) {
   if(this is c-udf)
       execute our code
   else
       execute previous code
}
```

**Comment by ZheyuanBu** [comment]
I was trying to insert some random numbers into a table (random is a internal function that returns a float).
```
drop table if exists b;
create table b(x float8, y float8);
insert into b values(random(), random());
```
However, those scripts can not pass the validation check at:
https://github.com/shlee0605/peloton/blob/udf/src/backend/bridge/dml/expr/expr_transformer.cpp#L306
and
https://github.com/shlee0605/peloton/blob/udf/src/backend/bridge/dml/expr/expr_transformer.cpp#L309

According to my understanding, in the first line, the assert statement does not let functions with no argument pass through. And in the second line, the `CheckUserDefinedFunction` does not let internal functions pass through.

Does it make sense to filtering out all internal functions and no argument functions? Because if I remove those two checks, the `insert into b values(random(), random());` can succeed.

**Comment by shlee0605** [comment]
@ZheyuanBu I checked with the peloton's most recent master branch. `random()` function is not supported in peloton. Only `select random()` will work since it only goes through postgres code path. So, let us not use `random()` function in our udf functions. I think you can implement one. 

Anyway, we need to check if postgres udf functions officially supports no arguments. If they do, we can remove `assert()`.
